# Generated by Django 4.2.4 on 2023-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("working_hours_start", models.TimeField()),
                ("working_hours_end", models.TimeField()),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("profile_picture", models.ImageField(upload_to="barbers/")),
                ("bio", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
