# Generated by Django 4.2.4 on 2023-08-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("barbers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("DO", "Day Off"),
                            ("SL", "Sick Leave"),
                            ("V", "Vacation"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="barbers.barber"
                    ),
                ),
            ],
        ),
    ]
