# Generated by Django 4.2.4 on 2023-08-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_servicetype_appointment_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.servicetype",
            ),
        ),
    ]
